/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameNumericKeyboardFields.java
 *
 * Created on 21.10.2010, 14:38:30
 */

package virtualkeyboard.test;

import java.io.IOException;
import java.util.Enumeration;
import java.util.Locale;
import java.util.Properties;
import javax.swing.UIManager;
import virtualkeyboard.gui.DialogVirtualKeyboardReal;


/**
 *
 * @author vladimir.petrenko
 */
public class FrameVirtualKeyboardTestPopUpReal extends javax.swing.JFrame {
    Properties langProp = null;
    Locale locale=null;

    /** Creates new form FrameNumericKeyboardFields */
    public FrameVirtualKeyboardTestPopUpReal() {
        initComponents();
        locale = Locale.getDefault();
        try {
            langProp = new Properties();
            langProp.load(getClass().getResourceAsStream("/virtualkeyboard/lang/Keyboard_lang.properties"));

            for (Enumeration e = langProp.propertyNames() ; e.hasMoreElements() ;) {
//                System.out.println(e.nextElement().toString());
                jComboBox.addItem(e.nextElement().toString());
            }
            jComboBox.setSelectedItem("de");
        } catch (IOException e) {
            System.err.println(e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        jLTextField = new javax.swing.JLabel();
        jLTextArea = new javax.swing.JLabel();
        jSPTextArea = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jLPasswd = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jScrollPane = new javax.swing.JScrollPane();
        jEditorPane = new javax.swing.JEditorPane();
        jLEditorPane = new javax.swing.JLabel();
        jFormattedTextField = new javax.swing.JFormattedTextField();
        jLFormatedTextField = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jCheckBoxAutoUp = new javax.swing.JCheckBox();
        jCheckBoxShiftBs = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test NumericKeyboard");

        jTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldMousePressed(evt);
            }
        });
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        jLTextField.setText("jTextField:");

        jLTextArea.setText("jTextArea:");

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextAreaMousePressed(evt);
            }
        });
        jSPTextArea.setViewportView(jTextArea);

        jLPasswd.setText("Passwd:");

        jPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordFieldMousePressed(evt);
            }
        });
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jEditorPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEditorPaneMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(jEditorPane);

        jLEditorPane.setText("EditorPane:");

        jFormattedTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldMouseClicked(evt);
            }
        });
        jFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldActionPerformed(evt);
            }
        });

        jLFormatedTextField.setText("FormatedTextField:");

        jComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxItemStateChanged(evt);
            }
        });

        jCheckBoxAutoUp.setText("AutoUp");

        jCheckBoxShiftBs.setText("ShiftBs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTextArea)
                            .addComponent(jLEditorPane)
                            .addComponent(jLTextField)
                            .addComponent(jLPasswd))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSPTextArea)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxAutoUp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxShiftBs, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFormatedTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxShiftBs, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(jCheckBoxAutoUp, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLTextField)
                        .addComponent(jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTextArea)
                    .addComponent(jSPTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPasswd)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEditorPane)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFormatedTextField)
                    .addComponent(jFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jTextField);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldMousePressed
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jTextField);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jTextFieldMousePressed

    private void jTextAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaMousePressed
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jTextArea);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jTextAreaMousePressed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jPasswordField);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordFieldMousePressed
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jPasswordField);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jPasswordFieldMousePressed

    private void jEditorPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEditorPaneMouseClicked
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jEditorPane);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jEditorPaneMouseClicked

    private void jFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldActionPerformed
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jFormattedTextField);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jFormattedTextFieldActionPerformed

    private void jFormattedTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMouseClicked
        DialogVirtualKeyboardReal dlg = new DialogVirtualKeyboardReal(this, false, jFormattedTextField);
        dlg.setPoitToUp(jCheckBoxAutoUp.isSelected());
        dlg.setShiftBs(jCheckBoxShiftBs.isSelected());
        dlg.setLocaleL(locale);
    }//GEN-LAST:event_jFormattedTextFieldMouseClicked

    private void jComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxItemStateChanged
        locale= new Locale((String)jComboBox.getSelectedItem());
    }//GEN-LAST:event_jComboBoxItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {}

                new FrameVirtualKeyboardTestPopUpReal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxAutoUp;
    private javax.swing.JCheckBox jCheckBoxShiftBs;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JEditorPane jEditorPane;
    private javax.swing.JFormattedTextField jFormattedTextField;
    private javax.swing.JLabel jLEditorPane;
    private javax.swing.JLabel jLFormatedTextField;
    private javax.swing.JLabel jLPasswd;
    private javax.swing.JLabel jLTextArea;
    private javax.swing.JLabel jLTextField;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jSPTextArea;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables

}
